### ISSUE TITLE
When write to dbf memo fields, in all records duplicated values from last record

### ISSUE THREAD

**Issue by egorbon** [jferard/JxBase#15]
When write data to new dbf-table with memo fields, memo fields in all records have same value from last record.
And dbt file is small, and you can see in it - only one memo field value from last record.
For writer using various types: XBaseFileTypeEnum.dBASE3plusMemo, XBaseFileTypeEnum.dBASE4Memo, XBaseFileTypeEnum.dBASE7Memo
[t123.zip](https://github.com/jferard/JxBase/files/6735130/t123.zip)
Original data: 
[Original.pdf](https://github.com/jferard/JxBase/files/6735339/Original.pdf)
Test for problem: 
[MemoTest.zip](https://github.com/jferard/JxBase/files/6739301/MemoTest.zip)

**Comment by jferard** [comment]
Thanks for reporting. I'll check this as soon as possible.

**Comment by jferard** [comment]
I can confirm that the `RawMemoWriter` (common to all types having memo fields) ifs faulty : the new offset is not correctly returned, hence the data is always written at block offset 1. I will fix it.

**Comment by jferard** [comment]
@egorbon I think it's fixed. Can you try the last version ?
